services:
  - type: web
    name: steam-copia-backend
    runtime: java
    plan: free
    rootDir: "steam copia/backend"
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: h2
      - key: JAVA_VERSION
        value: 17
      - key: JWT_SECRET
        value: esta-es-una-clave-secreta-muy-larga-y-segura-de-mas-de-32-caracteres
