services:
  # Backend
  - type: web
    name: steam-copia-backend
    env: java
    plan: free
    rootDir: backend
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: APP_SEED
        value: "true"
      - key: DB_URL
        value: jdbc:postgresql://db.twvdwbnujpbheoehnjpk.supabase.co:5432/postgres
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: Cagh12rbh09-
      - key: JWT_SECRET
        value: esta-es-una-clave-secreta-muy-larga-y-segura-de-mas-de-32-caracteres
      - key: JAVA_VERSION
        value: 17

  # Frontend (Static Site)
  - type: static
    name: steam-copia-frontend
    buildCommand: bash build.sh
    staticPublishPath: frontend/build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: API_BASE_URL
        value: https://steam-copia-backend.onrender.com
